### ISSUE TITLE
Provide a way to get a component key

### ISSUE THREAD

**Issue by alexeyBityukov** [DevExpress/testcafe-react-selectors#111]
I have several div with installed keys. Is it possible to get a div by the value of key?

**Comment by gothraven** [comment]
No it is not possible to do that, you can instead do something like this
```Javascript
<Toto key={x} id={x} ></Toto>
```
and select using the ```ReactSelector('Toto').withProps('id', x);```

**Comment by kirovboris** [comment]
Hi @alexBityuckov,

Unfortunately, it's impossible to get a component `key` now. I'll investigate the possibility to add this info in the future releases.

**Comment by Arawnh** [comment]
Is there any eta on this feature coming to live? @kirovboris Would be very helpful in our projet. :)

**Comment by kirovboris** [comment]
I've just published `testcafe-react-selectors@3.1.0`. 
https://github.com/DevExpress/testcafe-react-selectors#selecting-components-by-the-component-key
Since `3.0.1` the `getReact` method provides a component key.
https://github.com/DevExpress/testcafe-react-selectors#obtaining-components-props-and-state
