### ISSUE TITLE
Support getReact for React Hooks

### ISSUE THREAD

**Issue by MMahmal** [DevExpress/testcafe-react-selectors#142]
Hello,
First I wanted to say thanks for the amazing works! 

And second, I wanted to ask if someone was already working on the support of React Hooks. Because at the moment I cannot get the state or the props of a component using Hooks.

Thank you for your time :)
Cheers,
Mehdi

**Comment by LavrovArtem** [comment]
We will investigate the possibility of supporting React Hooks in the future.

**Comment by MMahmal** [comment]
Thanks for the quick reply!

If I have time I would like to offer my contribution. Do you guys already have a process in place?

Cheers.

**Comment by miherlosev** [comment]
Hi @MMahmal 

Thank you for your interest in the project.
Accessing the `props`  values should work correctly now.
See the following example:
```js
//Component tree:
<Container>
    <Child/>
</Container>

 //Components classes:
function Child(props) {
    return <span>{props.propName}</span>
}

function Container() {
    const [value, setState] = useState(0);    

    return (
        <div><Child propName={value}/></div>
    )
}

//Test code:
ReactSelector('Child').getReact(({props}) => props.propName);
```js


It's not easy to support hooks for the functional state
```js
 function myComponent() {
    const [value, setValue] = useState(0);

    return <div>{value}</div>
}
```
because we set variable names.

React DevTools has [an experimental support](https://github.com/bvaughn/react-devtools-experimental/blob/master/OVERVIEW.md#inspecting-hooks) of the React Hooks. But it doesn't work correctly in my machine.

Anyway, if you want to implement or improve support of React Hooks - you are welcome. Create a pull request and we will review it.
