### ISSUE TITLE
ReactSelector with HOC ?

### ISSUE THREAD

**Issue by thiphariel** [DevExpress/testcafe-react-selectors#157]
Hi,

I'm having trouble with HOC selection. Here is some of my component tree :
![image](https://user-images.githubusercontent.com/3125705/68379374-028b9380-014e-11ea-8a36-db460ee4e549.png)

As you can see, my "Board" component is wrap with 2 HOC (withRouter from react-router and connect from react-redux)

How to target it with ReactSelector ? Is that even possible ?

Thanks

**Comment by aleks-pro** [comment]
Hi @thiphariel ,

Thank you for your inquiry. This issue looks like a question that would be best [asked on StackOverflow](https://stackoverflow.com/questions/ask?tags=testcafe) - an amazing platform for users to ask and answer questions.

We try to keep the GitHub issues tracker for bugs and feature requests only (see also: [Contributing](https://github.com/DevExpress/testcafe#contributing)).

If you think that this issue is a bug, feel free to open a new issue, but please make sure to follow the bug template. Thank you in advance.
