### ISSUE TITLE
Can't get the element props value when a particular prop is an object

### ISSUE THREAD

**Issue by elzhu** [DevExpress/testcafe-react-selectors#166]
Hi There,
I am facing an issue when using react selector and try to get an element's prop value when a prop is an Object.

Firstly, I get my react element by:
`const inlinePlayer = await ReactSelector('e').withProps('accessibilityLabel', 'Embedded video').getReact();`

It gives me my target react element correctly. 

Next, I try to read a prop value from this target element by:
`const visibleVideoCount = inlinePlayer.props.playbackCoordination._players[0].placement.visibleFraction()`

However, I got "playbackCoordination: undefined" Which is incorrect since my "playbackCoordination" is an object that contains more information other than undefined.  When I try to get other prop value which is not an object, I will able to get the correct value fine. This issue only happen when I try to reach an object prop.

This is the Object prop structure:

**playbackCoordination**
{_autoPlayVideo: ƒ () {}, _canAutoPlay: ƒ () {}, _c…}
**_players**
[{…}]
**0**
{canAutoplay: true, commandHandlers: {…}, isLooping…}
canAutoplay
true
**placement**
{_visiblePart: {…}, isInViewport: ƒ () {}, item: {……}
top
ƒ () {}
**visibleFraction**
ƒ () {}

**Comment by Farfurix** [comment]
Hello,

Could you please share a sample project with us? We will examine it and check for a suitable solution.

**Comment by elzhu** [comment]
This is an industry project that will not able to share more detail there. :(  But i tried the main concern here is happening when prop is an object instead of a direct field.

**Comment by AlexKamaev** [comment]
@elzhu
Hello,

I assume that the issue occurs because your props contain functions. Functions are not serializable in JS, so the `getReact` method cannot return them from the client to the server correctly (and the test code is a server part).
As I understand, you want to execute the `visibleFraction` function:
`const visibleVideoCount = inlinePlayer.props.playbackCoordination._players[0].placement.visibleFraction()`

From what I gather, this function should be executed on the client side. When you try to execute it in the test, this means that you executed it on the server side, not in your browser.

If you have further questions, feel free to contact us.
