### ISSUE TITLE
Can't find desendant components of the same type

### ISSUE THREAD

**Issue by arubtsov** [DevExpress/testcafe-react-selectors#23]
I have two instances of a component one of which is desendant of another (with a div wrapper between them). `ReactSelector('Foo').count` returns 1.

**Comment by kirovboris** [comment]
Hi @leomelin,
Yes, the current implementation doesn't allow to use such selectors. I'm going to investigate and try to figure out a fix soon.

**Comment by joywave** [comment]
No idea how this issue still exists when such functionality is so common. For something like
```
Row
    Container
        Container key='1'
        Container key='2'
    Container
        ...
    Container
        ...
```
![image](https://user-images.githubusercontent.com/30377621/73489090-09eec180-4378-11ea-9936-b11609672f23.png)
How am I supposed to be able to select the containers with keys so that I can verify the key values are correct?

I'm able to select the first container fine with `section = ReactSelector('Row Container').nth(0);` but then selecting the two containers inside that is seemingly impossible.
- `section.findReact('Container');` does not work, it only returns the original container itself
- `section.findReact('Container Container').nth(x);` also does not work

What's even stranger is that at seemingly random times, `section.findReact('Container Container').nth(x);` does actually work, but not in any reproducible way.

The hack that I'm currently using is `section.find('.container').nth(0).findReact('Container').getReact(({ key }) => key))`

**Comment by alexey-lin** [comment]
Hi @joywave,

Thank you for your feedback and for the workaround. Once we get any results, we will post them here. You are also welcome to submit your PR.

**Comment by ilya2010ujl** [comment]
Hello
I encountered the same error. When searching for nested items with the same name. The reactive selector can only select the parent. For example
```
<ComponentA  key="componentAParent">
    <ComponentA key="componentAChild" />
    <ComponentB key="componentBChild" />
</ComponentA>
```
ReactSelector("ComponentA").withKey("componentAParent") - can find parent
but ReactSelector("ComponentA").withKey("componentAChild") - can't find the nested element

Could you please help us with this issue?

**Comment by Aleksey28** [comment]
Hi @ilya2010ujl,

I see that the problem is still actual. I'll reopen the issue.
